<?php
$view = new view();
$view->name = 'mean_value';
$view->description = '';
$view->tag = 'default';
$view->base_table = 'node';
$view->human_name = 'Μέση Τιμή Ρύπανσης';
$view->core = 7;
$view->api_version = '3.0';
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

/* Display: Master */
$handler = $view->new_display('default', 'Master', 'default');
$handler->display->display_options['title'] = 'Μέση Τιμή Ρύπανσης';
$handler->display->display_options['use_more_always'] = FALSE;
$handler->display->display_options['group_by'] = TRUE;
$handler->display->display_options['access']['type'] = 'perm';
$handler->display->display_options['cache']['type'] = 'none';
$handler->display->display_options['query']['type'] = 'views_query';
$handler->display->display_options['exposed_form']['type'] = 'basic';
$handler->display->display_options['pager']['type'] = 'full';
$handler->display->display_options['pager']['options']['items_per_page'] = '10';
$handler->display->display_options['style_plugin'] = 'table';
$handler->display->display_options['style_options']['columns'] = array(
    'title' => 'title',
    'field_content_records' => 'field_content_records',
    'field_content_records_1' => 'field_content_records_1',
    'field_longitude' => 'field_longitude',
    'field_latitude' => 'field_latitude',
);
$handler->display->display_options['style_options']['default'] = '-1';
$handler->display->display_options['style_options']['info'] = array(
    'title' => array(
        'sortable' => 0,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
    ),
    'field_content_records' => array(
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
    ),
    'field_content_records_1' => array(
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
    ),
    'field_longitude' => array(
        'sortable' => 0,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
    ),
    'field_latitude' => array(
        'sortable' => 0,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
    ),
);
/* Relationship: Content: Taxonomy terms on node */
$handler->display->display_options['relationships']['term_node_tid']['id'] = 'term_node_tid';
$handler->display->display_options['relationships']['term_node_tid']['table'] = 'node';
$handler->display->display_options['relationships']['term_node_tid']['field'] = 'term_node_tid';
$handler->display->display_options['relationships']['term_node_tid']['vocabularies'] = array(
    'taxonomy_station' => 'taxonomy_station',
    'tags' => 0,
    'taxonomy_pollution_type' => 0,
);
/* Field: Content: Title */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['label'] = '';
$handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
$handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
/* Field: AVG(Content: Καταγραφές) */
$handler->display->display_options['fields']['field_content_records']['id'] = 'field_content_records';
$handler->display->display_options['fields']['field_content_records']['table'] = 'field_data_field_content_records';
$handler->display->display_options['fields']['field_content_records']['field'] = 'field_content_records';
$handler->display->display_options['fields']['field_content_records']['group_type'] = 'avg';
$handler->display->display_options['fields']['field_content_records']['label'] = 'Μέση Τιμή Ρύπων';
$handler->display->display_options['fields']['field_content_records']['type'] = 'number_decimal';
$handler->display->display_options['fields']['field_content_records']['settings'] = array(
    'thousand_separator' => '',
    'decimal_separator' => '.',
    'scale' => '2',
    'prefix_suffix' => 1,
);
$handler->display->display_options['fields']['field_content_records']['delta_offset'] = '0';
/* Field: STDDEV_POP(Content: Καταγραφές) */
$handler->display->display_options['fields']['field_content_records_1']['id'] = 'field_content_records_1';
$handler->display->display_options['fields']['field_content_records_1']['table'] = 'field_data_field_content_records';
$handler->display->display_options['fields']['field_content_records_1']['field'] = 'field_content_records';
$handler->display->display_options['fields']['field_content_records_1']['group_type'] = 'stddev_pop';
$handler->display->display_options['fields']['field_content_records_1']['label'] = 'Τυπική Απόκλιση Ρύπων';
$handler->display->display_options['fields']['field_content_records_1']['type'] = 'number_decimal';
$handler->display->display_options['fields']['field_content_records_1']['settings'] = array(
    'thousand_separator' => '',
    'decimal_separator' => '.',
    'scale' => '2',
    'prefix_suffix' => 1,
);
$handler->display->display_options['fields']['field_content_records_1']['delta_offset'] = '0';
/* Field: Taxonomy term: Γεωγραφικό Μήκος */
$handler->display->display_options['fields']['field_longitude']['id'] = 'field_longitude';
$handler->display->display_options['fields']['field_longitude']['table'] = 'field_data_field_longitude';
$handler->display->display_options['fields']['field_longitude']['field'] = 'field_longitude';
$handler->display->display_options['fields']['field_longitude']['relationship'] = 'term_node_tid';
/* Field: Taxonomy term: Γεωγραφικό Πλάτος */
$handler->display->display_options['fields']['field_latitude']['id'] = 'field_latitude';
$handler->display->display_options['fields']['field_latitude']['table'] = 'field_data_field_latitude';
$handler->display->display_options['fields']['field_latitude']['field'] = 'field_latitude';
$handler->display->display_options['fields']['field_latitude']['relationship'] = 'term_node_tid';
$handler->display->display_options['fields']['field_latitude']['settings'] = array(
    'thousand_separator' => '',
    'decimal_separator' => '.',
    'scale' => '2',
    'prefix_suffix' => 1,
);
/* Sort criterion: Content: Post date */
$handler->display->display_options['sorts']['created']['id'] = 'created';
$handler->display->display_options['sorts']['created']['table'] = 'node';
$handler->display->display_options['sorts']['created']['field'] = 'created';
$handler->display->display_options['sorts']['created']['order'] = 'DESC';
/* Filter criterion: Content: Published */
$handler->display->display_options['filters']['status']['id'] = 'status';
$handler->display->display_options['filters']['status']['table'] = 'node';
$handler->display->display_options['filters']['status']['field'] = 'status';
$handler->display->display_options['filters']['status']['value'] = 1;
$handler->display->display_options['filters']['status']['group'] = 1;
$handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
/* Filter criterion: Content: Type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'node';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
    'record' => 'record',
);
/* Filter criterion: Content: Σταθμός (field_content_station) */
$handler->display->display_options['filters']['field_content_station_tid']['id'] = 'field_content_station_tid';
$handler->display->display_options['filters']['field_content_station_tid']['table'] = 'field_data_field_content_station';
$handler->display->display_options['filters']['field_content_station_tid']['field'] = 'field_content_station_tid';
$handler->display->display_options['filters']['field_content_station_tid']['exposed'] = TRUE;
$handler->display->display_options['filters']['field_content_station_tid']['expose']['operator_id'] = 'field_content_station_tid_op';
$handler->display->display_options['filters']['field_content_station_tid']['expose']['label'] = 'Σταθμός';
$handler->display->display_options['filters']['field_content_station_tid']['expose']['operator'] = 'field_content_station_tid_op';
$handler->display->display_options['filters']['field_content_station_tid']['expose']['identifier'] = 'field_content_station_tid';
$handler->display->display_options['filters']['field_content_station_tid']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
);
$handler->display->display_options['filters']['field_content_station_tid']['type'] = 'select';
$handler->display->display_options['filters']['field_content_station_tid']['vocabulary'] = 'taxonomy_station';
/* Filter criterion: Content: Τύπος Ρύπου (field_content_pollution) */
$handler->display->display_options['filters']['field_content_pollution_tid']['id'] = 'field_content_pollution_tid';
$handler->display->display_options['filters']['field_content_pollution_tid']['table'] = 'field_data_field_content_pollution';
$handler->display->display_options['filters']['field_content_pollution_tid']['field'] = 'field_content_pollution_tid';
$handler->display->display_options['filters']['field_content_pollution_tid']['exposed'] = TRUE;
$handler->display->display_options['filters']['field_content_pollution_tid']['expose']['operator_id'] = 'field_content_pollution_tid_op';
$handler->display->display_options['filters']['field_content_pollution_tid']['expose']['label'] = 'Τύπος Ρύπου';
$handler->display->display_options['filters']['field_content_pollution_tid']['expose']['operator'] = 'field_content_pollution_tid_op';
$handler->display->display_options['filters']['field_content_pollution_tid']['expose']['identifier'] = 'field_content_pollution_tid';
$handler->display->display_options['filters']['field_content_pollution_tid']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
);
$handler->display->display_options['filters']['field_content_pollution_tid']['type'] = 'select';
$handler->display->display_options['filters']['field_content_pollution_tid']['vocabulary'] = 'taxonomy_pollution_type';
/* Filter criterion: Content: Ημερομηνία (field_content_date) */
$handler->display->display_options['filters']['field_content_date_value']['id'] = 'field_content_date_value';
$handler->display->display_options['filters']['field_content_date_value']['table'] = 'field_data_field_content_date';
$handler->display->display_options['filters']['field_content_date_value']['field'] = 'field_content_date_value';
$handler->display->display_options['filters']['field_content_date_value']['operator'] = '>=';
$handler->display->display_options['filters']['field_content_date_value']['exposed'] = TRUE;
$handler->display->display_options['filters']['field_content_date_value']['expose']['operator_id'] = 'field_content_date_value_op';
$handler->display->display_options['filters']['field_content_date_value']['expose']['label'] = 'Ημερομηνία Από';
$handler->display->display_options['filters']['field_content_date_value']['expose']['operator'] = 'field_content_date_value_op';
$handler->display->display_options['filters']['field_content_date_value']['expose']['identifier'] = 'field_content_date_value';
$handler->display->display_options['filters']['field_content_date_value']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
);
/* Filter criterion: Content: Ημερομηνία (field_content_date) */
$handler->display->display_options['filters']['field_content_date_value_1']['id'] = 'field_content_date_value_1';
$handler->display->display_options['filters']['field_content_date_value_1']['table'] = 'field_data_field_content_date';
$handler->display->display_options['filters']['field_content_date_value_1']['field'] = 'field_content_date_value';
$handler->display->display_options['filters']['field_content_date_value_1']['operator'] = '<=';
$handler->display->display_options['filters']['field_content_date_value_1']['exposed'] = TRUE;
$handler->display->display_options['filters']['field_content_date_value_1']['expose']['operator_id'] = 'field_content_date_value_1_op';
$handler->display->display_options['filters']['field_content_date_value_1']['expose']['label'] = 'Ημερομηνία Έως';
$handler->display->display_options['filters']['field_content_date_value_1']['expose']['operator'] = 'field_content_date_value_1_op';
$handler->display->display_options['filters']['field_content_date_value_1']['expose']['identifier'] = 'field_content_date_value_1';
$handler->display->display_options['filters']['field_content_date_value_1']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
);

/* Display: Page */
$handler = $view->new_display('page', 'Page', 'page');
$handler->display->display_options['path'] = 'pollution-mean';
$handler->display->display_options['menu']['type'] = 'normal';
$handler->display->display_options['menu']['title'] = 'Μέση Τιμή Ρύπανσης';

/* Display: Services */
$handler = $view->new_display('services', 'Services', 'services_1');
$handler->display->display_options['path'] = 'rest-pollution-mean';
